#!/bin/bash
if [ ! -d ".git" ]; then
    echo "We have detected that you have downloaded antario-master.zip from the GitHub website. This is the WRONG way to download Antario. Please download Antario with the command 'git clone --recursive https://github.com/Wando1423/Antario.git'"
    exit
else
	git pull
	git submodule update --recursive --remote
	git pull --recurse-submodules
	cmake .
	make -j$(grep "^processor" /proc/cpuinfo | wc -l) "$@"
fi
